export {default as HomePage} from './HomePage'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Send} from './Send'
export {default as History} from './History'